services:
  mysql:
    image: mysql:8.0
    container_name: fx_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fxdb
      MYSQL_USER: fxuser
      MYSQL_PASSWORD: fxpass
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fxnet

  app:
    image: fx-deals-spring-app:latest
    container_name: fx_deals_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fxdb
      SPRING_DATASOURCE_USERNAME: fxuser
      SPRING_DATASOURCE_PASSWORD: fxpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - fxnet

networks:
  fxnet:
